### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Icekiss69** [dead-hosts/hpHosts---Ad-and-Tracking_web_hosts-file.net#1]
Hiya

would it be possible to get lists that use 0.0.0.0 instead of 127.0.0.1 ?
dnscrypt proxy uses 127.0.0.1 and ::1

https://github.com/DNSCrypt/dnscrypt-proxy

or a domain list without ip's instead of 127.0.0.1 for compatibility and security reasons

I am unable to use 127.0.0.1
https://hosts-file.net/ad_servers.txt

**Comment by funilrys** [comment]
Are you on Linux ?
